name: Destroy IaC

on:
  repository_dispatch:
    types: [destroy]

env:
  # Terraform
  TERRAFORM_VERSION: '0.12.29'

  # AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest
 
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Terraform Destroy
        run: | 
          terraform init
          terraform destroy -auto-approve